### ISSUE TITLE
Class skeeks\yii2\assetsAuto\AssetsAutoCompressComponent does not exist

### ISSUE THREAD

**Issue by MagSag** [skeeks-semenov/yii2-assets-auto-compress#10]
my configuration is  as follow:
```
'bootstrap'=>['assetsAutoCompress'],
 'components' => [
        'assetsAutoCompress' =>
        [
            'class'=>'skeeks\yii2\assetsAuto\AssetsAutoCompressComponent',
            'enabled'=> true,
            'jsCompress'=> true,
            'cssFileCompile'    => true,
            'jsFileCompile'     => true,
        ],]
```

But when I run the website I am getting the error : 

> Class skeeks\yii2\assetsAuto\AssetsAutoCompressComponent does not exist

Where I am wrong?

**Comment by skeeks-semenov** [comment]
@MagSag Are you sure you have updated composer?

**Comment by MagSag** [comment]
Yes my composer is updated; May be I don't understand what you mean by updating composer?
