### ISSUE TITLE
Compression on off not working

### ISSUE THREAD

**Issue by Er-Kalpesh** [skeeks-semenov/yii2-assets-auto-compress#17]
Here I have mark false for all still its compressing all css and js

'class'                         => '\skeeks\yii2\assetsAuto\AssetsAutoCompressComponent',
'enabled'                       => false,

'readFileTimeout'               => 3,           //Time in seconds for reading each asset file

'jsCompress'                    => false,        //Enable minification js in html code
'jsCompressFlaggedComments'     => false,        //Cut comments during processing js

'cssCompress'                   => true,        //Enable minification css in html code

'cssFileCompile'                => true,        //Turning association css files
'cssFileRemouteCompile'         => false,       //Trying to get css files to which the specified path as the remote file, skchat him to her.
'cssFileCompress'               => true,        //Enable compression and processing before being stored in the css file
'cssFileBottom'                 => false,       //Moving down the page css files
'cssFileBottomLoadOnJs'         => false,       //Transfer css file down the page and uploading them using js

'jsFileCompile'                 => false,        //Turning association js files
'jsFileRemouteCompile'          => false,       //Trying to get a js files to which the specified path as the remote file, skchat him to her.
'jsFileCompress'                => false,        //Enable compression and processing js before saving a file
'jsFileCompressFlaggedComments' => false,        //Cut comments during processing js

'htmlCompress'                  => true,        //Enable compression html
'htmlCompressOptions'           =>              //options for compressing output result
[
    'extra' => false,        //use more compact algorithm
    'no-comments' => true   //cut all the html comments
],     

How to turn off compression here ?

**Comment by skeeks-semenov** [comment]
@Er-Kalpesh 
Maybe I do not fully understand the question. Disable compression of css and js in a single file?
If so, it is necessary to set the options.

**Comment by skeeks-semenov** [comment]
'cssFileCompile' => false,
'jsFileCompile' => false,

**Comment by Er-Kalpesh** [comment]
yeah I have set false for all still its compressing into one line

**Comment by Er-Kalpesh** [comment]
and one more issue is I am getting error in firebug console like : SyntaxError: unterminated string literal

So any idea about that?

**Comment by Er-Kalpesh** [comment]
I have removed some of the plugins and updated composer and its working fine now. Thanks for great plugin.
