### ISSUE TITLE
Скорость склейки очень медленная

### ISSUE THREAD

**Issue by Igoreck** [skeeks-semenov/yii2-assets-auto-compress#23]
Заходя на страницы, на которых я не был - грузятся по 15 - 20 сек., что бы склеить стили со скриптами, а это очень долго. Так и должно быть или я что не правильно делаю?

**Comment by skeeks-semenov** [comment]
Вообще это может зависеть от разных факторов.
Мощность машины где работает проект.
Количество скриптов в сценарии где они склеиваются.
Еще есть настройки, когда каждый скрипт не просто склеивается но еще и минифицируется, а это тоже дополнительное время.

А вообще скорость это не ключевой момент. Потому как, чаще всегда есть 1-2 ну может 3 сценария в проекте где подлкючены разные скрипты. И генерируется файл один раз. Остальные читают кэшированные значения. Поменяется это дело только в момент релиза, и пока вы тестируете и смотрите релиз, подождете загрузки этих скриптов пусть даже 15-20 секунд.

**Comment by wartur** [comment]
@Igoreck вам надо группировать и использовать группу на группе страниц
AdminAsset
AgencyAsset
AppAsset
Тогда вообще скорость будет зашибенная и не будет 100500 раз все компилиться

И с внешними файлами есть трабла:
https://github.com/skeeks-semenov/yii2-assets-auto-compress/issues/21

**Comment by skeeks-semenov** [comment]
Скорость склейки решена локальным чтением файлов.
https://github.com/skeeks-semenov/yii2-assets-auto-compress/releases/tag/1.3.1.1
