### ISSUE TITLE
implode() func deprecated on PHP 7.4

### ISSUE THREAD

**Issue by haifahrul** [skeeks-semenov/yii2-assets-auto-compress#59]
```implode(): Passing glue string after array is deprecated. Swap the parameters```

![image](https://user-images.githubusercontent.com/6553704/97780421-22b22f00-1bb7-11eb-9905-a9802f3eb47a.png)

**Comment by skeeks-semenov** [comment]
Fixed: https://github.com/skeeks-semenov/yii2-assets-auto-compress/releases/tag/1.4.3.1
