### ISSUE TITLE
renderAjax course a bug

### ISSUE THREAD

**Issue by krissss** [skeeks-semenov/yii2-assets-auto-compress#6]
how to compress when use renderAjax ?

**Comment by skeeks-semenov** [comment]
@krissss 

I know about this bug, he recently came across this. Decisions until Uninvented (but still a lot I did not think on this subject)

Workaround in the project, do not use **renderAjax**
use:

```
public function actionYour()
    {
        $this->layout = false;
        return $this->render($this->action->id); //No ajax
    }
```

Or, in the scenario where the call will be used renderAyah otlyuchit work of this component

```
<?php
\Yii::$app->assetsAutoCompress->enabled = false;
?>
```

**Comment by krissss** [comment]
method one can not solve my problem, because my view need js.
if use method one, I think ***renderPartial* can be a greater method

method two can temporarily solve the problem, but it Is really not conducive to maintenance

**Comment by skeeks-semenov** [comment]
@krissss 

I agree with you.
I think that we'll find a way, let us leave the matter open to be solved.
